In [1]:
# PfDA Project
## Niall Horgan

In [2]:
import numpy as np
import pandas as pd

In [3]:
seed_value = 1
np.random.seed(seed_value)

var1 = np.random.randint(1, 11, 5)
print (var1)
print (var1[-1])

[ 6  9 10  6  1]
1


In [4]:
seed_value2 = 2
np.random.seed(seed_value2)

var2 = np.random.normal(1,11, 5)
print (var2)
print (var2[-1])

[ -3.58433632   0.3810649  -22.49815705  19.04297889 -18.72779144]
-18.727791437143495


In [5]:
var3 = np.random.rand(1,11,5)
print (var3)
print (var3[-1])

[[[0.20464863 0.61927097 0.29965467 0.26682728 0.62113383]
  [0.52914209 0.13457995 0.51357812 0.18443987 0.78533515]
  [0.85397529 0.49423684 0.84656149 0.07964548 0.50524609]
  [0.0652865  0.42812233 0.09653092 0.12715997 0.59674531]
  [0.226012   0.10694568 0.22030621 0.34982629 0.46778748]
  [0.20174323 0.64040673 0.48306984 0.50523672 0.38689265]
  [0.79363745 0.58000418 0.1622986  0.70075235 0.96455108]
  [0.50000836 0.88952006 0.34161365 0.56714413 0.42754596]
  [0.43674726 0.77655918 0.53560417 0.95374223 0.54420816]
  [0.08209492 0.3663424  0.8508505  0.40627504 0.02720237]
  [0.24717724 0.06714437 0.99385201 0.97058031 0.80025835]]]
[[0.20464863 0.61927097 0.29965467 0.26682728 0.62113383]
 [0.52914209 0.13457995 0.51357812 0.18443987 0.78533515]
 [0.85397529 0.49423684 0.84656149 0.07964548 0.50524609]
 [0.0652865  0.42812233 0.09653092 0.12715997 0.59674531]
 [0.226012   0.10694568 0.22030621 0.34982629 0.46778748]
 [0.20174323 0.64040673 0.48306984 0.50523672 0.38689265]
 